### ISSUE TITLE
Ranger doesn't start with gvim

### ISSUE THREAD

**Issue by etiennebatise** [Mizuchi/vim-ranger#6] opened 2015-07-23 12:59 UTC
Hi,

I use gvim, v7.4.778 on Archlinux. I have Ranger and vim-ranger installed by this [dotfile](https://github.com/joedicastro/dotfiles/tree/master/vim). It is working fine in terminal ViM.

Opening gvim et calling vim-ranger doesn't open the explorer and there are no error messages.

**Comment by Mizuchi** [comment] 2015-07-23 19:26
Confirmed. Thanks for reporting this issue. However it's not easy to fix. 
Due to ranger's limitation, you can't run it inside gvim at this point (you can try to run ":!ranger" in gvim). This is very much ranger's issue. The workaround here is opening ranger with a new virtual terminal, or integrating with Conque Shell. I probably won't fix this in a short-term since I don't even remember what's the last time I use gvim (I'll add a warning message when it's used inside gvim rather than vim). But patches are welcome.

**Closed as completed** 2015-08-04 19:41 UTC
Labels: bug, help wanted, wontfix
